services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: dev.underground.software
    volumes:
      - type: bind
        source: ./ssl
        target: /etc/ssl/nginx
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
      - target: 995
        published: 995
        protocol: tcp
        mode: host
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    volumes:
      - type: bind
        source: ./.git
        target: /var/git/singularity
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
    ports:
      - target: 9098
        published: 9098
        protocol: tcp
        mode: host
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: smtp
      args:
        hostname: dev.underground.software
    volumes:
      - type: bind
        source: ./email
        target: /mnt/email_data
        read_only: false
        selinux: z
    ports:
      - target: 465
        published: 11465
        protocol: tcp
        mode: host
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: pop
    volumes:
      - type: bind
        source: ./email/mail
        target: /mnt/mail
        read_only: true
        selinux: z
    ports:
      - target: 995
        published: 11995
        protocol: tcp
        mode: host
