services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
        NGINX_RUNTIME_SNIPPETS: 1
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./ssl
        target: /etc/ssl/nginx
        read_only: true
        selinux: z
      - type: bind
        source: ./nginx_snippets
        target: /etc/nginx/include.d
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    ports:
      - 1080:1080
      - 1443:1443
      - 1465:1465
      - 1995:1995
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./.git
        target: /var/git/singularity
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
    ports:
      - 9098:9098
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: smtp
      args:
        hostname: localhost
    volumes:
      - type: bind
        source: ./email
        target: /mnt/email_data
        read_only: false
        selinux: z
    ports:
      - 11465:465
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: pop
    volumes:
      - type: bind
        source: ./email/mail
        target: /mnt/mail
        read_only: true
        selinux: z
    ports:
      - 11995:995
