services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: kdlp.underground.software
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
    volumes:
      - type: bind
        source: ./ssl
        target: /etc/ssl/nginx
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    ports:
      - target: 1080
        published: 80
        protocol: tcp
        app_protocol: http
        mode: host
        name: "port for http connections to proxy"
      - target: 1443
        published: 443
        protocol: tcp
        app_protocol: https
        mode: host
        name: "port for https connections to proxy"
      - target: 1465
        published: 465
        protocol: tcp
        app_protocol: smtps
        mode: host
        name: "port for smtps connections to proxy"
      - target: 1995
        published: 995
        protocol: tcp
        app_protocol: pop3s
        mode: host
        name: "port for pop3s connections to proxy"
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    volumes:
      - type: bind
        source: ./.git
        target: /var/git/singularity
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
    ports:
      - target: 9098
        published: 9098
        protocol: tcp
        app_protocol: http
        mode: host
        name: "unencrypted http upstream server port"
    environment:
      - ORBIT_VERSION_INFO=singularity v0.1 https://github.com/underground-software/singularity
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: smtp
      args:
        hostname: kdlp.underground.software
        LISTEN_PORT: 1465
    volumes:
      - type: bind
        source: ./email
        target: /mnt/email_data
        read_only: false
        selinux: z
    ports:
      - target: 1465
        published: 11465
        protocol: tcp
        app_protocol: smtp
        mode: host
        name: "unencrypted smtp upstream server port"
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: pop
      args:
        LISTEN_PORT: 1995
    volumes:
      - type: bind
        source: ./email/mail
        target: /mnt/mail
        read_only: true
        selinux: z
    ports:
      - target: 1995
        published: 11995
        protocol: tcp
        app_protocol: pop3
        mode: host
        name: "unencrypted pop3 upstream server port"
