services:
  nginx:
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./nginx_snippets
        target: /etc/nginx/include.d
        read_only: true
      - type: bind
        source: ./docs
        target: /var/www/html
        read_only: true
  orbit:
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./docs
        target: /usr/local/share/orbit/docs
        read_only: true
