services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - nginx_snippet_source=./nginx_snippets
        - nginx_webroot_content=./kdlp.underground.software
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: localhost
        NGINX_HTTPS_LISTEN: 'unix:/run/nginx/socks/https.sock'
        NGINX_SMTPS_LISTEN: 'unix:/run/nginx/socks/smtps.sock'
        NGINX_POP3S_LISTEN: 'unix:/run/nginx/socks/pop3s.sock'
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./socks
        target: /run/nginx/socks
        read_only: false
        selinux: z
      - type: volume
        source: ssl-certs
        target: /etc/ssl/nginx
        read_only: true
      - type: bind
        source: ./nginx_snippets
        target: /etc/nginx/include.d
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    depends_on:
      - orbit
      - smtp
      - pop
    networks:
      - orbit
      - smtp
      - pop
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      additional_contexts:
        - orbit_singularity_git_dir=./.git
        - orbit_docs_source=./kdlp.underground.software
      target: orbit
      args:
        orbit_version_info: "singularity v0.1 (in development) https://github.com/underground-software/singularity"
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
      - type: volume
        source: orbit-db
        target: /var/orbit
        read_only: false
    networks:
      - orbit
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - tcp_server_source=./tcp_server
      target: smtp
      args:
        hostname: localhost
        LISTEN_PORT: 1465
    volumes:
      - type: volume
        source: email
        target: /mnt/email_data
        read_only: false
    networks:
      - smtp
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - tcp_server_source=./tcp_server
      target: pop
      args:
        LISTEN_PORT: 1995
    volumes:
      - type: volume
        source: email
        target: /mnt/email_data
        read_only: true
    depends_on:
      - smtp
    networks:
      - pop
networks:
  orbit:
  smtp:
  pop:
volumes:
  ssl-certs:
  email:
  orbit-db:
