services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: dev.underground.software
        NGINX_HTTPS_LISTEN: '[::]:1443 ipv6only=off'
        NGINX_SMTPS_LISTEN: '[::]:1465 ipv6only=off'
        NGINX_POP3S_LISTEN: '[::]:1995 ipv6only=off'
    volumes:
      - type: volume
        source: ssl-certs
        target: /etc/ssl/nginx
        read_only: true
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    ports:
      - target: 1443
        published: 443
        protocol: tcp
        app_protocol: https
        mode: host
        name: "port for https connections to proxy"
      - target: 1465
        published: 465
        protocol: tcp
        app_protocol: smtps
        mode: host
        name: "port for smtps connections to proxy"
      - target: 1995
        published: 995
        protocol: tcp
        app_protocol: pop3s
        mode: host
        name: "port for pop3s connections to proxy"
    depends_on:
      - orbit
      - smtp
      - pop
    networks:
      - orbit
      - smtp
      - pop
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
      args:
        orbit_version_info: "singularity v0.1 (staging) https://github.com/underground-software/singularity"
    volumes:
      - type: bind
        source: ./.git
        target: /var/git/singularity
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
    networks:
      - orbit
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: smtp
      args:
        hostname: dev.underground.software
        LISTEN_PORT: 1465
    volumes:
      - type: bind
        source: ./email
        target: /mnt/email_data
        read_only: false
        selinux: z
    networks:
      - smtp
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: pop
      args:
        LISTEN_PORT: 1995
    volumes:
      - type: bind
        source: ./email/mail
        target: /mnt/mail
        read_only: true
        selinux: z
    networks:
      - pop
networks:
  orbit:
  smtp:
  pop:
volumes:
  ssl-certs:
