services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - nginx_snippet_source=./nginx_snippets
        - nginx_webroot_content=./docs
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: ${SINGULARITY_HOSTNAME}
        NGINX_HTTPS_LISTEN: 'unix:/run/nginx/socks/https.sock'
        NGINX_SMTPS_LISTEN: 'unix:/run/nginx/socks/smtps.sock'
        NGINX_POP3S_LISTEN: 'unix:/run/nginx/socks/pop3s.sock'
    volumes:
      - type: bind
        source: ./socks
        target: /run/nginx/socks
        read_only: false
        bind:
          selinux: z
      - type: volume
        source: ssl-certs
        target: /etc/ssl/nginx
        read_only: true
    depends_on:
      - orbit
      - smtp
      - pop
    networks:
      - orbit
      - smtp
      - pop
      - submatrix
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      additional_contexts:
        - orbit_singularity_git_dir=./.git
        - orbit_docs_source=./docs
        - orbit_repos_source=./cgit_repos
        - mailman_source=./mailman
        - denis_source=./denis
      target: orbit
      args:
        orbit_version_info: "singularity ${SINGULARITY_VERSION} ${SINGULARITY_DEPLOYMENT_STATUS} https://github.com/underground-software/singularity"
    volumes:
      - type: volume
        source: orbit-db
        target: /var/lib/orbit
        read_only: false
      - type: volume
        source: submissions-db
        target: /var/lib/mailman
        read_only: true
      - type: volume
        source: denis-db
        target: /var/lib/denis
        read_only: true
    networks:
      - orbit
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - tcp_server_source=./tcp_server
      target: smtp
      args:
        hostname: ${SINGULARITY_HOSTNAME}
        LISTEN_PORT: 1465
    volumes:
      - type: volume
        source: email-mail
        target: /var/lib/email/mail
        read_only: false
      - type: volume
        source: email-logs
        target: /var/lib/email/logs
        read_only: false
    networks:
      - smtp
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - tcp_server_source=./tcp_server
      target: pop
      args:
        LISTEN_PORT: 1995
    volumes:
      - type: volume
        source: email-mail
        target: /var/lib/email/mail
        read_only: true
      - type: volume
        source: email-journal
        target: /var/lib/email/journal
        read_only: false
    depends_on:
      - smtp
    networks:
      - pop
  submatrix:
    build:
      context: submatrix
      dockerfile: Containerfile
      args:
        MATRIX_HOSTNAME: ${SINGULARITY_HOSTNAME}
    volumes:
      - type: volume
        source: submatrix-data
        target: /var/synapse
        read_only: false
    depends_on:
      - orbit
    networks:
      - submatrix
      - orbit
  mailman:
    build:
      context: mailman
      dockerfile: Containerfile
      additional_contexts:
        - watcher_source=./watcher
    volumes:
      - type: volume
        source: email-mail
        target: /var/lib/email/mail
        read_only: true
      - type: volume
        source: email-logs
        target: /var/lib/email/logs
        read_only: true
      - type: volume
        source: submissions-db
        target: /var/lib/mailman
        read_only: false
    depends_on:
      - smtp
    networks:
      - mailman
  denis:
    build:
      context: denis
      dockerfile: Containerfile
      additional_contexts:
        - run_at_source=./run-at
        - pop_source=./pop
        - mailman_source=./mailman
        - orbit_source=./orbit
      args:
        CHRONUS_HOSTNAME: ${SINGULARITY_HOSTNAME}
    volumes:
      - type: volume
        source: denis-db
        target: /var/lib/denis
        read_only: false
      - type: volume
        source: email-journal
        target: /var/lib/email/journal
        read_only: false
      - type: volume
        source: orbit-db
        target: /var/lib/orbit
        read_only: true
      - type: volume
        source: submissions-db
        target: /var/lib/mailman
        read_only: true
    networks:
      - denis
      - smtp
networks:
  orbit:
  smtp:
  pop:
  submatrix:
  mailman:
  denis:
volumes:
  ssl-certs:
  email-mail:
  email-logs:
  email-journal:
  orbit-db:
  submissions-db:
  submatrix-data:
  denis-db:
