services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: localhost
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
        NGINX_RUNTIME_SNIPPETS: 1
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./ssl
        target: /etc/ssl/nginx
        read_only: true
        selinux: z
      - type: bind
        source: ./nginx_snippets
        target: /etc/nginx/include.d
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /var/www/html
        read_only: true
        selinux: z
    ports:
      - target: 1080
        published: 1080
        protocol: tcp
        app_protocol: http
        mode: host
        name: "port for http connections to proxy"
      - target: 1443
        published: 1443
        protocol: tcp
        app_protocol: https
        mode: host
        name: "port for https connections to proxy"
      - target: 1465
        published: 1465
        protocol: tcp
        app_protocol: smtps
        mode: host
        name: "port for smtps connections to proxy"
      - target: 1995
        published: 1995
        protocol: tcp
        app_protocol: pop3s
        mode: host
        name: "port for pop3s connections to proxy"
    depends_on:
      - orbit
      - smtp
      - pop
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
      args:
        orbit_version_info: "singularity v0.1 (in development) https://github.com/underground-software/singularity"
    security_opt:
      - label:disable
    volumes:
      - type: bind
        source: ./.git
        target: /var/git/singularity
        read_only: true
        selinux: z
      - type: bind
        source: ./kdlp.underground.software
        target: /orbit/docs
        read_only: true
        selinux: z
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: smtp
      args:
        hostname: localhost
        LISTEN_PORT: 1465
    volumes:
      - type: bind
        source: ./email
        target: /mnt/email_data
        read_only: false
        selinux: z
    ports:
      - target: 1465
        published: 11465
        protocol: tcp
        app_protocol: smtp
        mode: host
        name: "unencrypted smtp upstream server port"
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_SOURCE=./tcp_server
      target: pop
      args:
        LISTEN_PORT: 1995
    volumes:
      - type: bind
        source: ./email/mail
        target: /mnt/mail
        read_only: true
        selinux: z
    ports:
      - target: 1995
        published: 11995
        protocol: tcp
        app_protocol: pop3
        mode: host
        name: "unencrypted pop3 upstream server port"
