FROM alpine:3.20 AS pop
RUN apk add \
	clang \
	make \
	;

RUN if [ "$COVERAGE" -eq 1 ]; then \
		apk add \
			clang-dev \
			compiler-rt \
			llvm-dev \
			gettext \
			bash \
			; \
	fi

COPY --from=tcp_server_source . /tcp_server
ARG LISTEN_PORT=995
RUN make -C /tcp_server CC='clang -static' DEFAULT_PORT=${LISTEN_PORT}

COPY --from=journal_source . /journal

COPY . /pop

RUN make -C /pop CC='clang -static'

RUN if [ "$COVERAGE" -eq 1 ]; then \
        make -C /pop CC='clang -static' SRVNAME=$hostname COVERAGE=1; \
    else \
        make -C /pop CC='clang -static' SRVNAME=$hostname; \
    fi

# FROM scratch as pop

RUN cp /tcp_server/tcp_server /usr/local/bin/tcp_server
RUN if [ "$COVERAGE" -eq 1 ]; then \
		cp /pop/pop3 /usr/local/bin/pop3_; \
		cp /pop/pop_wrapper /usr/local/bin/pop3; \
		mkdir -p /coverage; \
		chown 100:100 /coverage; \
		cp /pop/pop3.c /coverage/pop3.c; \
    else \
		cp /pop/pop3 /usr/local/bin/pop3; \
    fi

RUN rm -rf /tcp_server /pop /journal /pop

USER 100:100

ARG LISTEN_PORT=995
EXPOSE ${LISTEN_PORT}
ENTRYPOINT ["/usr/local/bin/tcp_server", "/usr/local/bin/pop3", "pop3", "/var/lib/email/mail", "/var/lib/email/journal/journal"]
