FROM alpine:3.20 AS build

RUN apk update && apk upgrade && apk add \
    envsubst \
    openssl \
    ;


ARG NGINX_HOSTNAME=localhost

RUN mkdir /etc/ssl/nginx && \
	cd /etc/ssl/nginx && \
	openssl \
		genpkey \
		-genparam \
		-algorithm DH \
		-pkeyopt dh_paramgen_prime_len:2048 \
		-out ssl-dhparams.pem && \
	 printf "[req]\n \
distinguished_name=req\n \
[ v3_ext ]\n \
subjectAltName=DNS:${NGINX_HOSTNAME},IP:127.0.0.1\n" > openssl.cnf \
	&& \
	:

RUN cd /etc/ssl/nginx && \
	openssl req \
		-x509 \
		-nodes \
		-days 133337 \
		-newkey rsa:2048 \
		-keyout privkey.pem \
		-out fullchain.pem \
		-subj "/CN=${NGINX_HOSTNAME}" \
		-extensions v3_ext \
		-config openssl.cnf \
	&& \
	:

COPY nginx.conf.template .

ARG NGINX_HTTPS_LISTEN='[::]:443 ipv6only=off'
ARG NGINX_SMTPS_LISTEN='[::]:465 ipv6only=off'
ARG NGINX_POP3S_LISTEN='[::]:995 ipv6only=off'

RUN envsubst \
	' \
		$NGINX_HOSTNAME \
		$NGINX_HTTPS_LISTEN \
		$NGINX_SMTPS_LISTEN \
		$NGINX_POP3S_LISTEN \
	' \
	< nginx.conf.template \
	> nginx.conf \
	;

FROM alpine:3.20 AS nginx

RUN apk update && apk upgrade && apk add \
    nginx          \
    nginx-mod-mail \
    nginx-mod-stream \
    tzdata \
    ;


RUN mkdir -p \
    /etc/nginx/include.d/root \
    /etc/nginx/include.d/events \
    /etc/nginx/include.d/http \
    /etc/nginx/include.d/server_https \
    /etc/nginx/include.d/server_http \
    /etc/nginx/include.d/mail \
    /etc/nginx/include.d/server_smtps \
    /etc/nginx/include.d/server_pop3s \
    ;

COPY --from=nginx_snippet_source . /etc/nginx/include.d/
COPY --from=nginx_webroot_content . /var/www/html

COPY --from=build nginx.conf /etc/nginx/
COPY --from=build /etc/ssl/nginx /etc/ssl/nginx

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
