ARG NGINX_RUNTIME_SNIPPETS=0

FROM alpine:3.19 AS build

RUN apk update && apk upgrade && apk add \
    envsubst \
    ;

COPY nginx.conf.template .

ARG NGINX_HOSTNAME=localhost
ARG NGINX_HTTP_PORT=80
ARG NGINX_HTTPS_PORT=443
ARG NGINX_SMTPS_PORT=465
ARG NGINX_POP3S_PORT=995

RUN envsubst '$NGINX_HOSTNAME:$NGINX_HTTP_PORT:$NGINX_HTTPS_PORT:$NGINX_SMTPS_PORT:$NGINX_POP3S_PORT' < nginx.conf.template > nginx.conf

FROM alpine:3.19 AS nginx-runtime-0

RUN apk update && apk upgrade && apk add \
    nginx          \
    nginx-mod-mail \
    nginx-mod-stream \
    ;


RUN mkdir -p \
    /etc/nginx/include.d/root \
    /etc/nginx/include.d/events \
    /etc/nginx/include.d/http \
    /etc/nginx/include.d/server_https \
    /etc/nginx/include.d/server_http \
    /etc/nginx/include.d/mail \
    /etc/nginx/include.d/server_smtps \
    /etc/nginx/include.d/server_pop3s \
    ;

COPY --from=nginx_snippet_source . /etc/nginx/include.d/

COPY --from=build nginx.conf /etc/nginx/

VOLUME /etc/ssl/nginx

ARG NGINX_HOSTNAME=localhost
ARG NGINX_HTTP_PORT=80
ARG NGINX_HTTPS_PORT=443
ARG NGINX_SMTPS_PORT=465
ARG NGINX_POP3S_PORT=995
EXPOSE ${NGINX_HTTP_PORT}
EXPOSE ${NGINX_HTTPS_PORT}
EXPOSE ${NGINX_SMTPS_PORT}
EXPOSE ${NGINX_POP3S_PORT}

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]

FROM nginx-runtime-0 AS nginx-runtime-1
VOLUME /etc/nginx/include.d/

FROM nginx-runtime-${NGINX_RUNTIME_SNIPPETS} AS nginx
