FROM alpine:3.20 AS build
RUN apk add \
	clang \
	make \
	;

COPY --from=watcher_source . /watcher

RUN make -C /watcher CC='clang -static'

FROM alpine:3.20 AS mailman

RUN apk add \
	py3-peewee \
	py3-gitpython \
	;


WORKDIR /usr/local/share/mailman

COPY . .

RUN mkdir -p /var/lib/mailman/ && \
	./db.py \
	:

RUN chown -R 100:100 /var/lib/mailman

COPY --from=build /watcher/watcher /usr/local/bin/watcher
COPY --from=denis_source . ./denis
COPY --from=orbit_source . ./orbit

VOLUME /var/lib/email/

USER 100:100

ENTRYPOINT ["/usr/local/bin/watcher", "/var/lib/email/logs", "submit.py"]
