FROM alpine:3.19 AS build

RUN apk update && apk upgrade && apk add \
	py3-peewee \
	envsubst \
	;

COPY . /orbit
WORKDIR /orbit

RUN mkdir -p /var/orbit/ && \
	./db.py \
	:

ARG orbit_version_info
RUN test -n "$orbit_version_info" || (echo 'version info is not set' && false) && \
	mv config.py config.py.template && \
	envsubst '$orbit_version_info' < config.py.template > config.py && \
	rm config.py.template \
	;

RUN mkdir \
	/var/git \
	/orbit/docs \
	/etc/cgit \
	;

COPY --from=orbit_singularity_git_dir . /var/git/singularity
COPY --from=orbit_docs_source . /orbit/docs
COPY --from=orbit_repos_source . /etc/cgit

FROM alpine:3.19 AS orbit

RUN apk update && apk upgrade && apk add \
	py3-bcrypt \
	py3-peewee \
	py3-markdown \
	uwsgi-python3 \
	uwsgi-http \
	cgit \
	;

WORKDIR /orbit

COPY --from=build /orbit /orbit
COPY --from=build /var/orbit /var/orbit
COPY --from=build /var/git /var/git
COPY --from=build /etc/cgit /etc/cgit

COPY cgitrc /etc/cgitrc

RUN chown -R 100:100 /orbit /var/orbit /var/git

USER 100:100

EXPOSE 9098

CMD ["uwsgi", "--plugin", "python,http", "./radius.ini"]
