FROM alpine:3.19 AS build

RUN apk update && apk upgrade && apk add \
	python3-dev \
	py3-pip \
	sqlite \
	build-base \
	libffi-dev \
	envsubst \
	;

COPY requirements.txt /requirements.txt
RUN python3 -m venv /radius-venv && \
	source /radius-venv/bin/activate && \
	pip install -r requirements.txt && \
	:

COPY . /orbit
WORKDIR /orbit

RUN sqlite3 /var/orbit/orbit.db ".read init-db.sql"

ARG orbit_version_info
RUN test -n "$orbit_version_info" || (echo 'version info is not set' && false) && \
	mv config.py config.py.template && \
	envsubst '$orbit_version_info' < config.py.template > config.py && \
	rm config.py.template \
	;

RUN mkdir \
	/var/git \
	/orbit/docs \
	;

COPY --from=ORBIT_SINGULARITY_GIT_DIR . /var/git/singularity
COPY --from=ORBIT_DOCS_SOURCE . /orbit/docs

FROM alpine:3.19 AS orbit

RUN apk update && apk upgrade && apk add \
	python3 \
	cgit \
	;

COPY --from=build /orbit /orbit
COPY --from=build /radius-venv /radius-venv
COPY --from=build /var/git /var/git
COPY --from=build /var/orbit /var/orbit

COPY cgitrc /etc/cgitrc

EXPOSE 9098

CMD /bin/sh -c "source /radius-venv/bin/activate && uwsgi /orbit/radius.ini"
