FROM alpine:3.19 AS build
RUN apk add \
	clang \
	clang-dev \
	compiler-rt \
	llvm-dev \
	git \
	make \
	;
	

COPY --from=tcp_server_source . /tcp_server
ARG LISTEN_PORT=465
RUN make -C /tcp_server CC='clang -static' DEFAULT_PORT=${LISTEN_PORT}

COPY . /smtp

ARG hostname
RUN test -n "$hostname" || (echo 'hostname is not set' && false)

ARG coverage

RUN if [ "$coverage" -eq 1 ]; then \
        make -C /smtp CC='clang -static' SRVNAME=$hostname COVERAGE=1; \
    else \
        make -C /smtp CC='clang -static' SRVNAME=$hostname; \
    fi

RUN mkdir -p /var/lib/email/mail /var/lib/email/logs && \
	chown 100:100 /var/lib/email/mail /var/lib/email/logs && \
	:

# Set correct permissions for /smtp directory (to copy coverage files later)
RUN chown -R 100:100 /smtp

FROM alpine:3.19 AS smtp
RUN apk add \
	clang \
	clang-dev \
	compiler-rt \
	make \
	;

COPY --from=build /var/lib/email /var/lib/email
VOLUME /var/lib/email/
COPY --from=build /tcp_server/tcp_server /usr/local/bin/tcp_server
COPY --from=build /smtp/smtp /usr/local/bin/smtp

# Copy coverage files
COPY --from=build /smtp /smtp
VOLUME /smtp

USER 100:100

ARG LISTEN_PORT=465
EXPOSE ${LISTEN_PORT}
ENTRYPOINT ["/usr/local/bin/tcp_server", "/usr/local/bin/smtp", "smtp", "/var/lib/email/mail", "/var/lib/email/logs"]
