FROM alpine:3.19 AS build
RUN apk add \
	clang \
	make \
	;

COPY --from=tcp_server_source . /tcp_server
ARG LISTEN_PORT=465
RUN make -C /tcp_server CC='clang -static' DEFAULT_PORT=${LISTEN_PORT}

COPY . /smtp

ARG hostname
RUN test -n "$hostname" || (echo 'hostname is not set' && false)

RUN make -C /smtp CC='clang -static' SRVNAME=$hostname

RUN mkdir -p /mnt/email_data/mail /mnt/email_data/logs && \
	chown -R 100:100 /mnt/email_data && \
	:

FROM scratch as smtp

COPY --from=build /mnt /mnt
VOLUME /mnt/email_data/
COPY --from=build /tcp_server/tcp_server /usr/local/bin/tcp_server
COPY --from=build /smtp/smtp /usr/local/bin/smtp

USER 100:100

ARG LISTEN_PORT=465
EXPOSE ${LISTEN_PORT}
ENTRYPOINT ["/usr/local/bin/tcp_server", "/usr/local/bin/smtp", "smtp", "/mnt/email_data"]
