FROM alpine:3.19 AS build
RUN apk add \
	clang \
	make \
	;

COPY --from=watchtower_source . /watchtower

RUN make -C /watchtower CC='clang -static' watcher

FROM alpine:3.19 AS denis

RUN apk add \
	py3-peewee \
	;


WORKDIR /usr/local/share/denis

COPY . .

RUN mkdir -p /var/lib/denis/ && \
	./db.py \
	:

RUN chown -R 100:100 /var/lib/denis

COPY --from=build /watchtower/watcher /usr/local/bin/watcher

VOLUME /mnt/email_data/

USER 100:100

ENTRYPOINT ["/usr/local/bin/watcher", "/mnt/email_data/logs", "submit.py"]
