FROM alpine:3.20 AS build
RUN apk add \
	clang \
	make \
	;

COPY --from=run_at_source . /run-at

RUN make -C /run-at CC='clang -static'

COPY --from=journal_source . /journal

RUN make -C /journal CC='clang -static'

RUN mkdir -p /var/lib/email/journal && \
	/journal/init_journal /var/lib/email/journal/journal && \
	chown -R 100:100 /var/lib/email/journal && \
	:

FROM alpine:3.20 AS denis

RUN apk add \
	py3-peewee \
	py3-gitpython \
	;

WORKDIR /usr/local/share/denis
COPY . .

COPY --from=mailman_source . ./mailman
COPY --from=orbit_source . ./orbit

RUN mkdir -p /var/lib/denis && \
	./db.py \
	:

RUN chown -R 100:100 /var/lib/denis

COPY --from=build /run-at/run-at /usr/local/bin/run-at
COPY --from=build /journal/restrict_access /usr/local/bin/restrict_access
COPY --from=build /journal/init_journal /usr/local/bin/init_journal
COPY --from=build /journal/append_journal /usr/local/bin/append_journal
COPY --from=build /var/lib/email/ /var/lib/email/


USER 100:100

ENTRYPOINT ["/usr/local/share/denis/start.py"]
