FROM alpine:3.20 AS build
RUN apk add \
	clang \
	make \
	envsubst \
	;

COPY --from=run_at_source . /run-at

RUN make -C /run-at CC='clang -static'

COPY --from=pop_source . /pop

RUN make -C /pop CC='clang -static' restrict_access

WORKDIR /usr/local/share/denis
COPY . .

ARG CHRONUS_HOSTNAME
RUN test -n "$CHRONUS_HOSTNAME " || (echo 'CHRONUS_HOSTNAME is not set' && false) && \
	mv config.py config.py.template && \
	envsubst '$CHRONUS_HOSTNAME' < config.py.template > config.py && \
	rm config.py.template \
	;

FROM alpine:3.20 AS denis

RUN apk add \
	py3-peewee \
	py3-curl \
	;

WORKDIR /usr/local/share/denis

COPY --from=build /usr/local/share/denis .
COPY --from=mailman_source . ./mailman
COPY --from=orbit_source . ./orbit

RUN mkdir -p /var/lib/denis && \
	./db.py \
	:

RUN chown -R 100:100 /var/lib/denis

COPY --from=build /run-at/run-at /usr/local/bin/run-at
COPY --from=build /pop/restrict_access /usr/local/bin/restrict_access

USER 100:100

ENTRYPOINT ["/usr/local/share/denis/start.py"]
