FROM alpine:3.20 AS build

RUN apk update && apk upgrade && apk add \
	envsubst \
	;

COPY . /usr/local/share/api
WORKDIR /usr/local/share/api

ARG singularity_version_info
RUN test -n "$singularity_version_info" || (echo 'version info is not set' && false) && \
	mv config.py config.py.template && \
	envsubst '$singularity_version_info' < config.py.template > config.py && \
	rm config.py.template \
	;

FROM alpine:3.20 AS api

RUN apk update && apk upgrade && apk add \
	py3-peewee \
	py3-markdown \
	uwsgi-python3 \
	uwsgi-http \
	tzdata \
	;

WORKDIR /usr/local/share/api

COPY --from=build /usr/local/share/api /usr/local/share/api
COPY --from=mailman_source . ./mailman
COPY --from=denis_source . ./denis

RUN chown -R 100:100 /usr/local/share/api

USER 100:100

EXPOSE 9077

CMD ["./start.sh"]
